export const APP_VERSION = '2.0.0';
export const RULE_VERSION = 'TRA-public-guidance-2026-09-08';
export const SOURCES = {
  individual: {name:'TRA · Income tax for individuals', url:'https://www.tra.go.tz/page/income-tax-for-individuals'},
  starting: {name:'TRA · Starting a business',url:'https://www.tra.go.tz/page/starting-business-income-for-individuals-and-paying-taxes'},
  vat: {name:'TRA · Value added tax',url:'https://www.tra.go.tz/page/value-added-tax-vat'},
  budget: {name:'Government budget speech 2026/27',url:'https://www.tra.go.tz/images/uploads/public_notice/english/HOTUBA_YA_BAJETI_YA_SERIKALI_2026-2027.pdf'},
  portal:{name:'Official TRA Taxpayer Portal',url:'https://taxpayerportal.tra.go.tz/'},
  support:{name:'TRA · Contact and services',url:'https://www.tra.go.tz/'},
};
export const CATEGORIES = ['Sales','Stock','Transport','Utilities','Rent','Equipment','Services','Other'];
export const TODAY = new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Dar_es_Salaam',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const money = n => new Intl.NumberFormat('en-TZ',{maximumFractionDigits:0}).format(n || 0);
export const escapeHTML = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function validDate(v){if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false; const d=new Date(v+'T12:00:00Z');return !isNaN(d)&&d.toISOString().slice(0,10)===v;}
export function parseAmount(v){const raw=String(v ?? '').trim();if(!/^(?:\d+|\d{1,3}(?:,\d{3})+)(?:\.0{1,2})?$/.test(raw))return NaN;const s=raw.replace(/,/g,'');const n=Number(s);return Number.isSafeInteger(n)&&n<=100000000000?n:NaN;}
export function validateRecord(r){const errors={}; if(!['sale','expense'].includes(r.type))errors.type='Choose a sale or expense.';if(!validDate(r.date)||r.date>TODAY)errors.date='Choose a valid date, today or earlier.';if(!r.description?.trim()||r.description.length>300)errors.description='Enter a description of up to 300 characters.';if(!Number.isSafeInteger(r.amount)||r.amount<=0||r.amount>100000000000)errors.amount='Enter a positive amount in whole TZS (maximum 100 billion).';if(!CATEGORIES.includes(r.category))errors.category='Choose a category.';if(r.seller?.length>150)errors.seller='Use a name of up to 150 characters.';if(r.reference?.length>80)errors.reference='Use a reference of up to 80 characters.';if(!['Cash','Mobile money','Bank','Other'].includes(r.payment))errors.payment='Choose a payment method.';if(r.vat!==null&&r.vat!==undefined&&(!Number.isSafeInteger(r.vat)||r.vat<0||r.vat>r.amount))errors.vat='Printed tax must be between zero and the total.';return errors;}
export function suggestCategory(text,type='expense'){
 if(type==='sale')return {category:'Sales',reason:'You selected a sale.',matched:[]};
 const words=String(text).toLowerCase().normalize('NFKD');
 const dictionary={Stock:['stock','supplier','supplies','wholesale','rice','flour','sugar','cement','mchele','unga','sukari','bidhaa','saruji','mboga'],Transport:['fuel','delivery','bus','taxi','transport','petrol','nauli','mafuta','usafiri'],Utilities:['electricity','water','airtime','internet','tanesco','luku','umeme','maji'],Rent:['rent','lease','pango'],Equipment:['equipment','printer','laptop','machine','vifaa'],Services:['repair','service','consulting','plumbing','huduma','matengenezo']};
 const matches=Object.entries(dictionary).map(([category,keys])=>({category,matched:keys.filter(k=>new RegExp('\\b'+k+'\\b','i').test(words))})).filter(x=>x.matched.length);
 if(matches.length!==1)return {category:'Other',reason:matches.length?'Several categories match. Please choose.':'No clear category match. Please choose.',matched:matches.flatMap(x=>x.matched)};
 return {...matches[0],reason:'Suggested from “'+matches[0].matched.join(', ')+'”. Review before saving.'};
}
export function parseReceipt(text){
 const lines=String(text).split(/\r?\n/).map(s=>s.trim()).filter(Boolean);
 const amounts=s=>(s.match(/(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d{1,2})?/g)||[]).map(s=>Number(s.replace(/,/g,''))).filter(Number.isFinite);
 const totals=lines.filter(l=>/\b(grand total|total amount|amount paid|total|jumla|kiasi)\b/i.test(l)&&!/subtotal|sub total|tax total|vat total|change|balance/i.test(l));
 const totalLine=totals.find(l=>/grand total|total amount|amount paid|jumla/i.test(l))||totals[totals.length-1];
 let amount=totalLine?amounts(totalLine).at(-1):null;
 if(!Number.isSafeInteger(amount))amount=null;
 const taxLine=lines.find(l=>/^(vat|tax|kodi)(?:\s|:)/i.test(l));
 let vat=taxLine?amounts(taxLine).at(-1):null;if(vat>amount||!Number.isSafeInteger(vat))vat=null;
 let date='';const iso=String(text).match(/\b(20\d{2})[-/](\d{1,2})[-/](\d{1,2})\b/);
 const numeric=String(text).match(/\b(\d{1,2})[/-](\d{1,2})[/-](20\d{2})\b/);
 const named=String(text).match(/\b(\d{1,2})\s+(Jan\w*|Feb\w*|Mar\w*|Apr\w*|May|Jun\w*|Jul\w*|Aug\w*|Sep\w*|Oct\w*|Nov\w*|Dec\w*)\s+(20\d{2})\b/i);
 if(iso)date=iso[1]+'-'+iso[2].padStart(2,'0')+'-'+iso[3].padStart(2,'0');
 else if(numeric)date=numeric[3]+'-'+numeric[2].padStart(2,'0')+'-'+numeric[1].padStart(2,'0');
 else if(named){const m=['jan','feb','mar','apr','may','jun','jul','aug','sep','oct','nov','dec'].indexOf(named[2].slice(0,3).toLowerCase())+1;date=named[3]+'-'+String(m).padStart(2,'0')+'-'+named[1].padStart(2,'0');}
 if(!validDate(date))date='';
 const seller=lines.find(l=>/[a-z]{3}/i.test(l)&&!/sample|fictional|receipt|risiti|invoice|not a fiscal|date|total|tin:/i.test(l))||'';
 const reference=String(text).match(/(?:receipt\s*(?:no|number)?|invoice\s*(?:no|number)?|reference|ref|risiti)\s*[:#.-]\s*([a-z0-9-]+)/i)?.[1]||'';
 return {amount,date,seller:seller.slice(0,150),vat,reference,uncertain:[...(!amount?['amount']:[]),...(!date?['date']:[]),...(numeric&&Number(numeric[1])<=12&&Number(numeric[2])<=12?['date format']:[]),...(!seller?['seller']:[])],text:String(text).slice(0,30000)};
}
export function findDuplicates(records,r){return records.filter(x=>x.id!==r.id&&x.status!=='void'&&((r.sourceHash&&x.sourceHash===r.sourceHash)||(x.date===r.date&&x.amount===r.amount&&x.type===r.type&&x.seller?.trim().toLowerCase()===r.seller?.trim().toLowerCase()&&x.seller?.trim())));}
export function totals(records,month=''){const confirmed=records.filter(r=>r.status==='confirmed'&&(!month||r.date.startsWith(month)));const sales=confirmed.filter(r=>r.type==='sale').reduce((a,r)=>a+r.amount,0);const expenses=confirmed.filter(r=>r.type==='expense').reduce((a,r)=>a+r.amount,0);return {sales,expenses,balance:sales-expenses,confirmed:confirmed.length,pending:records.filter(r=>r.status==='review'&&(!month||r.date.startsWith(month))).length};}
export function calculatePresumptive({turnover,completeRecords,resident=true,business='retail',year='2026',fullYearConfirmed=false,newBusiness=false}){
 const base={ruleVersion:RULE_VERSION,source:SOURCES.individual,assumptions:['Annual turnover; expenses are not subtracted.','General retail, resident individual, business-only income.','No election out of presumptive rules; no special-sector treatment.'],status:'blocked',amount:null};
 if(!Number.isSafeInteger(turnover)||turnover<0||turnover>100000000000)return {...base,reason:'Enter a valid non-negative annual turnover in whole TZS.'};
 if(!fullYearConfirmed)return {...base,reason:'Confirm that this is your full-year turnover or full-year projection.'};
 if(String(year)!=='2026')return {...base,reason:'This rule snapshot supports 2026 only. Confirm rules for the selected year.'};
 if(!resident||business!=='retail')return {...base,reason:'This calculator covers resident individual retailers. Your business needs a different assessment.'};
 if(newBusiness)return {...base,reason:'New-business relief requires TRA eligibility confirmation. No exemption is granted by this prototype.'};
 if(turnover>200000000)return {...base,reason:'Turnover is outside the published presumptive threshold. Request the appropriate assessment.'};
 if(turnover>11000000)return {...base,reason:'Verification needed: the current TRA page lists 4%, while the 2026/27 budget speech proposed 4.5%. The calculator withholds this band until the enacted rate and application date are confirmed.',conflictSource:SOURCES.budget};
 let amount=0,formula='Turnover up to TZS 4,000,000 → nil estimate.';
 if(turnover>4000000&&turnover<=7000000){amount=completeRecords?Math.round((turnover-4000000)*0.03):100000;formula=completeRecords?'3% × (TZS '+money(turnover)+' − TZS 4,000,000)':'Incomplete records: fixed TZS 100,000.';}
 if(turnover>7000000){amount=completeRecords?90000+Math.round((turnover-7000000)*0.03):250000;formula=completeRecords?'TZS 90,000 + 3% × (TZS '+money(turnover)+' − TZS 7,000,000)':'Incomplete records: fixed TZS 250,000.';}
 return {...base,status:'estimate',amount,formula,reason:'Planning estimate, subject to applicable law and TRA verification.'};
}
export function csv(records){const q=v=>'"'+String(v??'').replace(/^\s*[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';return '\uFEFF'+[['Date','Type','Description','Seller or customer','Amount TZS','Printed tax TZS','Category','Payment','Reference','Status','Record ID'],...records.map(r=>[r.date,r.type,r.description,r.seller,r.amount,r.vat??'',r.category,r.payment,r.reference,r.status,r.id])].map(r=>r.map(q).join(',')).join('\r\n');}
export function calendarEvent({id,title,date,description=''}){if(!validDate(date))throw Error('Invalid calendar date');const esc=s=>String(s).replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/[,;]/g,'\\$&');const next=new Date(date+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+1);return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//TIDRE//Personal reminders//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:'+id+'@tidre.demo','DTSTAMP:'+new Date().toISOString().replace(/[-:]|\.\d{3}/g,''),'DTSTART;VALUE=DATE:'+date.replaceAll('-',''),'DTEND;VALUE=DATE:'+next.toISOString().slice(0,10).replaceAll('-',''),'SUMMARY:'+esc(title),'DESCRIPTION:'+esc(description),'BEGIN:VALARM','TRIGGER:-P1D','ACTION:DISPLAY','DESCRIPTION:'+esc(title),'END:VALARM','END:VEVENT','END:VCALENDAR',''].join('\r\n');}
export const ARTICLES=[
 {id:'records',title:['Why keep records?','Kwa nini nihifadhi kumbukumbu?'],terms:['record','receipt','risiti','kumbukumbu','expense','stock'],text:['Record each sale and expense, retain its evidence, and check the date and total. Categories organize the ledger; they do not determine VAT treatment.','Rekodi kila mauzo na matumizi, hifadhi ushahidi na hakiki tarehe na jumla. Aina za kumbukumbu haziamui VAT.'],source:'individual',action:'capture'},
 {id:'tin',title:['How do I register for a TIN?','Ninasajilije TIN?'],terms:['tin','register','registration','sajili','usajili'],text:['Use TRA’s official registration guidance and portal. Required identity and business documents depend on your situation. This prototype does not verify TINs or collect passwords.','Tumia maelekezo rasmi na mfumo wa TRA. Nyaraka hutegemea hali yako. Mfano huu hauthibitishi TIN wala kukusanya nywila.'],source:'starting'},
 {id:'vat',title:['What is VAT?','VAT ni nini?'],terms:['vat','value added','ongezeko'],text:['VAT is a tax on taxable supplies. Registration, exemptions and input-tax eligibility matter. A printed VAT figure is evidence to review, not an automatic entitlement to deduct it.','VAT ni kodi ya ongezeko la thamani. Usajili, misamaha na masharti ya makato ni muhimu. Kiasi kilicho kwenye risiti hakimaanishi moja kwa moja kuwa kinaweza kukatwa.'],source:'vat'},
 {id:'estimate',title:['How does my estimate work?','Makadirio yanafanyaje kazi?'],terms:['tax','estimate','calculate','turnover','kodi','makadirio','hesabu'],text:['For eligible individual traders, presumptive estimates use annual turnover and record status. Open the calculator to review eligibility, assumptions and the rule snapshot.','Makadirio ya walipakodi wanaostahili hutumia mauzo ya mwaka na hali ya kumbukumbu. Fungua kikokotoo uhakiki masharti na chanzo.'],source:'individual',action:'tax'},
 {id:'payment',title:['How do I pay or submit?','Ninalipaje au kuwasilisha?'],terms:['pay','payment','ussd','lipa','malipo','submit','file','return','ritani','wasilisha'],text:['Prepare and review your records here, then use the official TRA Taxpayer Portal. No payment or filing takes place in this prototype. Keep the official confirmation from TRA.','Andaa na uhakiki kumbukumbu hapa, kisha tumia mfumo rasmi wa TRA. Mfano huu haupokei malipo wala kuwasilisha ritani. Hifadhi uthibitisho wa TRA.'],source:'portal'},
 {id:'penalty',title:['I missed a deadline. What next?','Nimechelewa. Nifanye nini?'],terms:['late','penalt','fine','faini','chelewa','adhabu','deadline'],text:['Check your obligation and period in the official portal, then contact TRA for case-specific guidance. This guide does not calculate penalties or promise a waiver.','Hakiki wajibu na kipindi katika mfumo rasmi, kisha wasiliana na TRA. Mwongozo huu hauhesabu faini wala kuahidi msamaha.'],source:'support'},
 {id:'efd',title:['Can this issue an EFD receipt?','Huu unaweza kutoa risiti ya EFD?'],terms:['efd','vfd','fiscal','electronic receipt'],text:['The downloadable receipt here is a business record marked “Not a fiscal receipt”. Fiscal issuance and validation require an approved TRA service or provider.','Risiti inayopakuliwa hapa ni kumbukumbu ya biashara iliyoandikwa “Not a fiscal receipt”. Risiti ya kodi inahitaji huduma iliyoidhinishwa na TRA.'],source:'support'},
 {id:'relief',title:['Is my new business exempt?','Biashara yangu mpya ina msamaha?'],terms:['new business','relief','exempt','mpya','msamaha'],text:['New-business relief is conditional. Eligibility and the application must be confirmed with TRA; this app will not grant the relief automatically.','Msamaha wa biashara mpya una masharti. Thibitisha sifa na maombi kwa TRA; programu hii haitoi msamaha yenyewe.'],source:'individual'},
];
export function searchGuidance(query){const q=String(query).toLowerCase();const scored=ARTICLES.map(a=>({article:a,score:a.terms.reduce((s,t)=>s+(q.includes(t)?t.length:0),0)})).filter(x=>x.score).sort((a,b)=>b.score-a.score);return scored.slice(0,3).map(x=>x.article);}
export function seedState(){const month=TODAY.slice(0,7);const day=i=>month+'-'+String(Math.min(i,Number(TODAY.slice(-2)))).padStart(2,'0');const rows=[['sale',108000,'Daily shop sales','Cash customers','Sales'],['sale',125000,'Rice and household goods','Cash customers','Sales'],['expense',88000,'Wholesale stock','Mwanga Supplies','Stock'],['sale',96000,'Daily shop sales','Cash customers','Sales'],['expense',56000,'Flour and sugar stock','Mtoni Wholesale','Stock'],['sale',120000,'Rice and cooking oil','Cash customers','Sales'],['expense',72000,'Shop rent contribution','Market office','Rent'],['sale',135000,'Daily shop sales','Cash customers','Sales'],['expense',45000,'Rice delivery','Mwanga Supplies','Stock'],['sale',84000,'Household goods','Cash customers','Sales'],['expense',18000,'Electricity top-up','Utility example','Utilities'],['sale',98000,'Daily shop sales','Cash customers','Sales'],['expense',37000,'Stock transport','Transport example','Transport'],['sale',76000,'Morning sales','Cash customers','Sales']];return {version:2,profile:{name:"Amina’s Market",location:'Dar es Salaam',mode:'sample'},records:rows.map((r,i)=>({id:'sample-'+(i+1),type:r[0],amount:r[1],description:r[2],seller:r[3],category:r[4],payment:i%3?'Cash':'Mobile money',date:day(Math.min(Math.floor(i/2)+1,8)),vat:null,reference:'EX-'+String(i+1).padStart(3,'0'),status:'confirmed',source:'sample',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})).concat([{id:'sample-review-1',type:'expense',amount:59000,description:'Supplier delivery — check total',seller:'Mtoni Wholesale',category:'Stock',payment:'Cash',date:day(7),status:'review',vat:null,reference:'EX-R01',source:'sample'},{id:'sample-review-2',type:'expense',amount:12500,description:'Transport receipt — confirm details',seller:'Transport example',category:'Transport',payment:'Cash',date:day(8),status:'review',vat:null,reference:'EX-R02',source:'sample'}]),events:[],reminders:[],savedEstimate:null};}
export function validateBackup(input){if(!input||input.version!==2||!Array.isArray(input.records)||input.records.length>5000)throw Error('This is not a supported TIDRE backup.');const seen=new Set();return input.records.map(r=>{const clean={id:String(r.id||'').slice(0,100),type:r.type,date:r.date,description:String(r.description||'').slice(0,300),seller:String(r.seller||'').slice(0,150),amount:r.amount,vat:r.vat??null,category:r.category,payment:r.payment,reference:String(r.reference||'').slice(0,80),status:r.status,source:'import',createdAt:r.createdAt,updatedAt:r.updatedAt};if(!clean.id||seen.has(clean.id)||Object.keys(validateRecord(clean)).length||!['confirmed','review','void'].includes(clean.status))throw Error('Backup contains invalid or repeated records. No changes were made.');seen.add(clean.id);return clean;});}
