import {escapeHTML as e, money} from './core.js';

export function reviewCases(records) {
  return records.filter(r => r.status !== 'void').map(r => {
    const matches = records.filter(other => other.id !== r.id && other.status !== 'void' && (
      (r.sourceHash && r.sourceHash === other.sourceHash) ||
      (r.reference && r.reference === other.reference && r.seller === other.seller && r.date === other.date && r.type === other.type && r.amount === other.amount)
    ));
    const reasons = [];
    if (r.status === 'review') reasons.push(['Details await confirmation', 'Taarifa zinasubiri uthibitisho']);
    if (matches.length) reasons.push(['Matching receipt records', 'Kumbukumbu za risiti zinazofanana']);
    if (['ocr','pdf-text'].includes(r.source) && !r.reference) reasons.push(['Receipt reference needs checking','Namba ya risiti inahitaji uhakiki']);
    return {record:r, matches, reasons, signature:JSON.stringify([r.updatedAt,r.status,r.date,r.seller,r.reference,r.amount,r.sourceHash,matches.map(x=>x.id).sort()])};
  }).filter(c => c.reasons.length);
}

export function officerView(state, selectedId, t) {
  const cases = reviewCases(state.records);
  const reviewed = c => state.officerReviews?.[c.record.id]?.signature === c.signature;
  const count = cases.filter(c=>!reviewed(c)).length;
  const chosen = cases.find(c=>c.record.id===selectedId);
  const status = c => `<span class="badge ${reviewed(c)?'confirmed':'review'}">${reviewed(c)?t('Review recorded','Uhakiki umehifadhiwa'):t('Needs review','Inahitaji uhakiki')}</span>`;
  const overview = `<div class="page-header"><div><div class="eyebrow">${t('OFFICER WORKSPACE · DEMONSTRATION','ENEO LA AFISA · MFANO')}</div><h1>${t('Evidence before a decision.','Ushahidi kabla ya uamuzi.')}</h1><p>${t('Review the reason, inspect the source and record the next step.','Hakiki sababu, chunguza chanzo na hifadhi hatua inayofuata.')}</p></div><button class="btn" data-action="navigate" data-route="overview">${t('Business workspace','Eneo la biashara')}</button></div><div class="officer-metrics"><section class="card"><span class="muted">${t('Awaiting officer review','Zinasubiri afisa')}</span><strong>${count}</strong></section><section class="card"><span class="muted">${t('Reviews recorded','Uhakiki uliohifadhiwa')}</span><strong>${cases.length-count}</strong></section><section class="card"><span class="muted">${t('Source','Chanzo')}</span><strong class="officer-source">${t('This workspace','Eneo hili')}</strong></section></div>`;
  if (!chosen) return overview+`<section class="card"><div class="card-head"><h2>${t('Review queue','Orodha ya uhakiki')}</h2><span class="small muted">${cases.length} ${t('cases','kesi')}</span></div>${cases.length?cases.map(c=>`<div class="officer-row"><div><strong>${e(c.record.description)}</strong><p class="small muted">${e(c.record.seller)} · TZS ${money(c.record.amount)}</p><p class="small">${c.reasons.map(r=>t(...r)).join(' · ')}</p>${status(c)}</div><button class="btn primary" data-action="officer-case" data-id="${e(c.record.id)}">${t('Review evidence','Hakiki ushahidi')}</button></div>`).join(''):`<div class="empty"><h2>${t('No records need review','Hakuna kumbukumbu za kuhakiki')}</h2><p>${t('Pending confirmations, matching receipts and unreadable references appear here.','Uthibitisho unaosubiri, risiti zinazofanana na namba zisizosomwa huonekana hapa.')}</p></div>`}</section><p class="note small">${t('Review signals support a person’s decision. They do not establish tax evasion or an official assessment. This preview uses the records on this device; it is not a TRA account.','Ishara hizi zinasaidia uamuzi wa mtu. Hazithibitishi ukwepaji kodi au tathmini rasmi. Mfano huu hutumia kumbukumbu za kifaa hiki; si akaunti ya TRA.')}</p>`;
  const r=chosen.record, decision=reviewed(chosen)?state.officerReviews[r.id]:null;
  const pair=(label,value)=>`<div class="officer-fact"><span>${label}</span><strong>${e(value||'—')}</strong></div>`;
  return overview+`<div class="buttons" style="margin-bottom:18px"><button class="btn" data-action="officer-back">${t('Back to queue','Rudi kwenye orodha')}</button>${status(chosen)}</div><div class="split"><section class="card"><h2>${t('Why this record was flagged','Sababu ya kuhitaji uhakiki')}</h2><ul class="officer-reasons">${chosen.reasons.map(reason=>`<li>${t(...reason)}</li>`).join('')}</ul>${pair(t('Supplier','Muuzaji'),r.seller)}${pair(t('Date','Tarehe'),r.date)}${pair(t('Receipt reference','Namba ya risiti'),r.reference)}${pair(t('Total','Jumla'),'TZS '+money(r.amount))}${pair(t('Source method','Njia ya chanzo'),r.source)}${chosen.matches.length?`<div class="note warning">${t('Matching records','Kumbukumbu zinazofanana')}: ${chosen.matches.map(x=>e(x.id)).join(', ')}</div>`:''}<div class="buttons" style="margin-top:20px">${r.sourceId?`<button class="btn" data-action="download-source" data-id="${e(r.id)}">${t('Download source receipt','Pakua risiti ya asili')}</button>`:''}<button class="btn" data-action="edit-record" data-id="${e(r.id)}">${t('Open record for correction','Fungua kurekebisha')}</button></div><p class="small muted">${t('Official verification has not been performed.','Uhakiki rasmi haujafanyika.')}</p><a class="source-link" href="https://verify.tra.go.tz/Home/Index" target="_blank" rel="noopener noreferrer">${t('Open TRA receipt verification','Fungua uhakiki rasmi wa TRA')} ↗</a></section><section class="card"><h2>${t('Record the review','Hifadhi uhakiki')}</h2>${decision?`<div class="note"><strong>${decision.outcome==='clarify'?t('Clarification needed','Ufafanuzi unahitajika'):t('Review completed','Uhakiki umekamilika')}</strong><p>${e(decision.note)}</p><span class="small muted">${e(new Date(decision.at).toLocaleString())}</span></div>`:`<div class="field"><label for="officer-outcome">${t('Next step','Hatua inayofuata')}</label><select id="officer-outcome"><option value="clarify">${t('Clarification needed','Ufafanuzi unahitajika')}</option><option value="reviewed">${t('Review completed','Uhakiki umekamilika')}</option></select></div><div class="field" style="margin-top:18px"><label for="officer-note">${t('Reason / evidence checked','Sababu / ushahidi uliohakikiwa')}</label><textarea id="officer-note" rows="4" maxlength="500" placeholder="${t('Explain what you checked and the next step.','Eleza ulichohakiki na hatua inayofuata.')}"></textarea></div><p id="officer-error" class="form-errors" role="alert"></p><button class="btn primary" data-action="officer-save" data-id="${e(r.id)}">${t('Save review','Hifadhi uhakiki')}</button>`}<p class="small muted" style="margin-top:20px">${t('Saved locally with a timestamp. No message, penalty or assessment is sent. Correcting the source record makes it eligible for a fresh review.','Huhifadhiwa kwenye kifaa pamoja na muda. Hakuna ujumbe, adhabu au tathmini inayotumwa. Kurekebisha kumbukumbu huwezesha uhakiki mpya.')}</p></section></div>`;
}
